### ISSUE TITLE
How to kill a process in HIRES PRV Status Monitor.

### ISSUE THREAD

**Issue by lshuai310** [Caltech-IPAC/hiresprv#34]
I am a beginner for HIRES-PRV code，and I want to ask a simple question that the way to cancel an active work running in PRV server. I try to use the command Status('prv.cookies').cancel()   to cancel a job, but it can not run with an error of  JSONDecodeError: Expecting value: line 1 column 1 (char 0).

**Comment by bjfultn** [comment]
Hello, my apologies for the delayed response. We are working hard on an upcoming release that will go out at the end of the month. 

The cancel command should work as called, but you might try initializing the Status object first separately and then running cancel.

```
status = Status('prv.cookies')
status.cancel()
```

Its also possible that your workspace is in a weird state due to errors and/or our fiddling around with the server while testing the upgrade. If thats the case I can manually remove the busy state and allow you to continue processing.

**Comment by lshuai310** [comment]
Hello,

I think my workspace is in a weird state due to errors​,  because  just one sentence "File deactivated [vdaa22233_r20070827.290]."displayed in PrvMonitor for two weeks. If possible, I wish you could remove my busy state​, and  my KOA ID is lshuai.

Thank you!

**Comment by bjfultn** [comment]
There is now a new cancel button on the monitor page that will allow the user to get out of this stuck state on their own.
